create table generos
(
    id     bigint generated by default as identity,
    nombre varchar(50) not null,
    primary key (id)
);
create table peliculas
(
    id             bigint generated by default as identity,
    calificacion   double,
    fecha_creacion date,
    titulo         varchar(255) not null,
    genero_id      bigint,
    primary key (id)
);
create table personajes
(
    id       bigint generated by default as identity,
    edad     integer      not null,
    historia varchar(255),
    nombre   varchar(255) not null,
    peso     double,
    primary key (id)
);
create table personajes_asociados_apeliculas
(
    personaje_id bigint not null,
    pelicula_id  bigint not null
);
alter table generos
    add constraint UK_9u5buu0dehagjdoqm3wv6orm3 unique (nombre);

alter table peliculas
    add constraint UK_ropvo38gu64eson5q4dnf0mw2 unique (titulo);

alter table personajes
    add constraint UK_huqg771sp2m6si3fho616y4wk unique (edad);

alter table personajes
    add constraint UK_lvf39kjqnknjok94lljt5ra6u unique (nombre);

alter table peliculas
    add constraint FKfty0as0fblr2te2ict41vewm1
        foreign key (genero_id)
            references generos;

alter table personajes_asociados_apeliculas
    add constraint FK2poq3q4tul522ruhgjn8notne
        foreign key (pelicula_id)
            references personajes;

alter table personajes_asociados_apeliculas
    add constraint FKpslhwek0kdjsix2cgsa2j7igc
        foreign key (personaje_id)
            references peliculas;

